# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ef0591e34ec7eea36c9a00967044b0c1823ad7c178f16bf0b9141c9971764c5dfb3dc57da5e0eab98b7dff8a8566e4e84c248a59418cf249324095c60fee369

test:
  secret_key_base: 033bf0f29613d5d9577678315c00e3c05185b47b2fa56e75711e62670b43b3d80ca85f7fe11d750502887d06560190c933b0503e9a9576a4cdb1b524ce2a101b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
